version: '3'
services:
    php:
        build:
          context: .
          dockerfile: ./.docker/Dockerfile
        container_name: projeto10
        ports:
          - 82:80
        volumes:
          - ./:/var/www/html